<?php namespace Fritzandandre\ThreeColumnWysiwygWidgetExtension\ThreeColumnWysiwygWidget;

use Anomaly\Streams\Platform\Model\BootstrapWidgets\BootstrapWidgetsThreeColumnWysiwygEntryModel;

class ThreeColumnWysiwygWidgetModel extends BootstrapWidgetsThreeColumnWysiwygEntryModel {}
